# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/VIVADO_program/look_ahead_adder_X064/displayer_X064/displayer/displayer.cache/wt [current_project]
set_property parent.project_path F:/VIVADO_program/look_ahead_adder_X064/displayer_X064/displayer/displayer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  F:/VIVADO_program/look_ahead_adder_X064/displayer_X064/displayer/data_cnt.vhd
  F:/VIVADO_program/look_ahead_adder_X064/displayer_X064/displayer/segment.vhd
  F:/VIVADO_program/look_ahead_adder_X064/displayer_X064/displayer/top.vhd
}
synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
